// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalApi.Data;

#nullable disable

namespace MinimalApi.Data.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20241110020558_OtherChanges")]
    partial class OtherChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinimalApi.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TodoItems", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("TodoItemsHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 394, DateTimeKind.Utc).AddTicks(5192),
                            IsCompleted = false,
                            Title = "Todo Item 1",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 394, DateTimeKind.Utc).AddTicks(5230),
                            IsCompleted = false,
                            Title = "Todo Item 2",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 394, DateTimeKind.Utc).AddTicks(5248),
                            IsCompleted = false,
                            Title = "Todo Item 3",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 394, DateTimeKind.Utc).AddTicks(5272),
                            IsCompleted = false,
                            Title = "Todo Item 4",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 394, DateTimeKind.Utc).AddTicks(5394),
                            IsCompleted = false,
                            Title = "Todo Item 5",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 394, DateTimeKind.Utc).AddTicks(5429),
                            IsCompleted = false,
                            Title = "Todo Item 6",
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 394, DateTimeKind.Utc).AddTicks(5449),
                            IsCompleted = false,
                            Title = "Todo Item 7",
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 394, DateTimeKind.Utc).AddTicks(5488),
                            IsCompleted = false,
                            Title = "Todo Item 8",
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 394, DateTimeKind.Utc).AddTicks(5515),
                            IsCompleted = false,
                            Title = "Todo Item 9",
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 394, DateTimeKind.Utc).AddTicks(5534),
                            IsCompleted = false,
                            Title = "Todo Item 10",
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 394, DateTimeKind.Utc).AddTicks(5572),
                            IsCompleted = false,
                            Title = "Todo Item 11",
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 394, DateTimeKind.Utc).AddTicks(5605),
                            IsCompleted = false,
                            Title = "Todo Item 12",
                            UserId = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 394, DateTimeKind.Utc).AddTicks(5695),
                            IsCompleted = false,
                            Title = "Todo Item 13",
                            UserId = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 394, DateTimeKind.Utc).AddTicks(5739),
                            IsCompleted = false,
                            Title = "Todo Item 14",
                            UserId = 1
                        },
                        new
                        {
                            Id = 15,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 394, DateTimeKind.Utc).AddTicks(5762),
                            IsCompleted = false,
                            Title = "Todo Item 15",
                            UserId = 1
                        },
                        new
                        {
                            Id = 16,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 394, DateTimeKind.Utc).AddTicks(5784),
                            IsCompleted = false,
                            Title = "Todo Item 16",
                            UserId = 1
                        },
                        new
                        {
                            Id = 17,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 394, DateTimeKind.Utc).AddTicks(5801),
                            IsCompleted = false,
                            Title = "Todo Item 17",
                            UserId = 1
                        },
                        new
                        {
                            Id = 18,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 394, DateTimeKind.Utc).AddTicks(5821),
                            IsCompleted = false,
                            Title = "Todo Item 18",
                            UserId = 1
                        },
                        new
                        {
                            Id = 19,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 394, DateTimeKind.Utc).AddTicks(5844),
                            IsCompleted = false,
                            Title = "Todo Item 19",
                            UserId = 1
                        },
                        new
                        {
                            Id = 20,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 394, DateTimeKind.Utc).AddTicks(5863),
                            IsCompleted = false,
                            Title = "Todo Item 20",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("MinimalApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<int>("PermitLimit")
                        .HasColumnType("int");

                    b.Property<int>("RateLimitWindowInMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("UsersHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 142, DateTimeKind.Utc).AddTicks(8431),
                            Email = "user1@example.com",
                            Password = "R1OP2CHvCht05DPQdNqEebuxg80pbIXpox5S7jieo/U=",
                            PermitLimit = 60,
                            RateLimitWindowInMinutes = 5,
                            Salt = "YLi1LuoI+awbyuUy9EqJlA==",
                            Username = "user1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 155, DateTimeKind.Utc).AddTicks(7363),
                            Email = "user2@example.com",
                            Password = "46dOi++b8pp+wnb52kVCUOX+Zz6ZipzvLRaqExHZdyM=",
                            PermitLimit = 60,
                            RateLimitWindowInMinutes = 5,
                            Salt = "LbF0O6EJhA+1rWVr7K7iPw==",
                            Username = "user2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 168, DateTimeKind.Utc).AddTicks(951),
                            Email = "user3@example.com",
                            Password = "F458HWoWuESQUhDNXH2B8lpoJ5TkZFofHX029/QLvjU=",
                            PermitLimit = 60,
                            RateLimitWindowInMinutes = 5,
                            Salt = "Sp3FBJKDR+a3ntfGouOd7Q==",
                            Username = "user3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 180, DateTimeKind.Utc).AddTicks(6534),
                            Email = "user4@example.com",
                            Password = "DOYYlKYN/MQ0+0czVKZPMPgySyGWCcRCdkt3VRCTSyU=",
                            PermitLimit = 60,
                            RateLimitWindowInMinutes = 5,
                            Salt = "fXn/NJfymsY3fLAmlKjIHA==",
                            Username = "user4"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 193, DateTimeKind.Utc).AddTicks(123),
                            Email = "user5@example.com",
                            Password = "rCrsXQ7h0hKdR1FvEZgsaC6GpGG7p7cFmNdNNpQOdF4=",
                            PermitLimit = 60,
                            RateLimitWindowInMinutes = 5,
                            Salt = "7RueG+tgj5t889UqVnoTGg==",
                            Username = "user5"
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 206, DateTimeKind.Utc).AddTicks(1842),
                            Email = "user6@example.com",
                            Password = "eOSB5NSy440/6kEE8DTsaYrH2g6gPcNlypFeSdciw28=",
                            PermitLimit = 60,
                            RateLimitWindowInMinutes = 5,
                            Salt = "rhnWS13/zQmwAsqa2lFaqA==",
                            Username = "user6"
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 218, DateTimeKind.Utc).AddTicks(7315),
                            Email = "user7@example.com",
                            Password = "DlnHhC+Mwz2128rT7lJ5Iwvgca7Ncg44LmcLa5RRu4s=",
                            PermitLimit = 60,
                            RateLimitWindowInMinutes = 5,
                            Salt = "ctJtLshAT+Kcgb3aeM4ZMg==",
                            Username = "user7"
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 231, DateTimeKind.Utc).AddTicks(2523),
                            Email = "user8@example.com",
                            Password = "Z1Wa/TAgcIIWdnh30G8u6oex9BrjcQmOzWt31bFQNOc=",
                            PermitLimit = 60,
                            RateLimitWindowInMinutes = 5,
                            Salt = "dnzxC3rjGWzBIDk3Gzba8w==",
                            Username = "user8"
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 243, DateTimeKind.Utc).AddTicks(8903),
                            Email = "user9@example.com",
                            Password = "xpp6ajsKviHIAJeyiDLrwsM3cqDBhh0toXdZ3cJlG0M=",
                            PermitLimit = 60,
                            RateLimitWindowInMinutes = 5,
                            Salt = "gp66v6DiItk1kpCY0htGIw==",
                            Username = "user9"
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 256, DateTimeKind.Utc).AddTicks(4583),
                            Email = "user10@example.com",
                            Password = "p8ZBK+5Uk64f6M+3lHerqPYuSnBKOzQC9HuYVvn2BZo=",
                            PermitLimit = 60,
                            RateLimitWindowInMinutes = 5,
                            Salt = "YaEUy9eBdlNYjA8kk7HUqQ==",
                            Username = "user10"
                        },
                        new
                        {
                            Id = 11,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 268, DateTimeKind.Utc).AddTicks(9454),
                            Email = "user11@example.com",
                            Password = "+4UVXk0avggCJUPJ+zQkd7OZ1jkCqPNXhS+nzXmAZJ8=",
                            PermitLimit = 60,
                            RateLimitWindowInMinutes = 5,
                            Salt = "wpJ6S3NzNnE+6aRlIWhOnA==",
                            Username = "user11"
                        },
                        new
                        {
                            Id = 12,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 282, DateTimeKind.Utc).AddTicks(1688),
                            Email = "user12@example.com",
                            Password = "B3zrzPvyk1IQVBk/YXaN2cV0IbvBF9XA7RNP6VlmhYs=",
                            PermitLimit = 60,
                            RateLimitWindowInMinutes = 5,
                            Salt = "rxcM/rYUj/sgLPjaHcEUgA==",
                            Username = "user12"
                        },
                        new
                        {
                            Id = 13,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 296, DateTimeKind.Utc).AddTicks(3987),
                            Email = "user13@example.com",
                            Password = "vNYV5ezTys5hwk0vpuLaaDSB9lUmRV3eBuBIlOIsM64=",
                            PermitLimit = 60,
                            RateLimitWindowInMinutes = 5,
                            Salt = "FPpKOs/y1Qzv5BWF5IbhTQ==",
                            Username = "user13"
                        },
                        new
                        {
                            Id = 14,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 312, DateTimeKind.Utc).AddTicks(1762),
                            Email = "user14@example.com",
                            Password = "CjqiVxdsK0cDZ+WECz1boGtMyzk4dyL4by7q36P8GLo=",
                            PermitLimit = 60,
                            RateLimitWindowInMinutes = 5,
                            Salt = "nyRTVJ+Fe2AaHxgHD6TRXQ==",
                            Username = "user14"
                        },
                        new
                        {
                            Id = 15,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 327, DateTimeKind.Utc).AddTicks(4533),
                            Email = "user15@example.com",
                            Password = "tC1JEGTtS8qNHq6Q7tkCzyr0WijB+HBr5xyojIkGsFI=",
                            PermitLimit = 60,
                            RateLimitWindowInMinutes = 5,
                            Salt = "Kw8+zJyTYQ2DV900dOz0lQ==",
                            Username = "user15"
                        },
                        new
                        {
                            Id = 16,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 339, DateTimeKind.Utc).AddTicks(7105),
                            Email = "user16@example.com",
                            Password = "K+w6DavBl3vlgUd5FuzJzytMgiWhfTx4BN9NcZMzkSE=",
                            PermitLimit = 60,
                            RateLimitWindowInMinutes = 5,
                            Salt = "a6RXVeCC+bBJ/HXtRA46OQ==",
                            Username = "user16"
                        },
                        new
                        {
                            Id = 17,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 351, DateTimeKind.Utc).AddTicks(9898),
                            Email = "user17@example.com",
                            Password = "MotSsq6FI+Lj3yGFZ1B8R4Dbe8AvZJIn6wgWuM1IX68=",
                            PermitLimit = 60,
                            RateLimitWindowInMinutes = 5,
                            Salt = "47WKubHvPIulISqbb9Hw+w==",
                            Username = "user17"
                        },
                        new
                        {
                            Id = 18,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 367, DateTimeKind.Utc).AddTicks(4377),
                            Email = "user18@example.com",
                            Password = "qCGn9itDdbQmT8O0DW3s0Fdm87svllcUPyogOb166P8=",
                            PermitLimit = 60,
                            RateLimitWindowInMinutes = 5,
                            Salt = "oSCB2cvFYpk2YaUgn0bNUQ==",
                            Username = "user18"
                        },
                        new
                        {
                            Id = 19,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 382, DateTimeKind.Utc).AddTicks(2281),
                            Email = "user19@example.com",
                            Password = "AMJCNcRtbvfrQB5Gp73oEafrEeyq4ZbhmTneMDzE8Do=",
                            PermitLimit = 60,
                            RateLimitWindowInMinutes = 5,
                            Salt = "oO14BlJIJK3ieAU8c78zHw==",
                            Username = "user19"
                        },
                        new
                        {
                            Id = 20,
                            CreatedOn = new DateTime(2024, 11, 10, 2, 5, 58, 394, DateTimeKind.Utc).AddTicks(5115),
                            Email = "user20@example.com",
                            Password = "3MPWg8I6mRwDpqUsKPfSFJZli50H/WSMHhOC/9W+/u8=",
                            PermitLimit = 60,
                            RateLimitWindowInMinutes = 5,
                            Salt = "IpdtDwe5x+csCHuyJcHsMA==",
                            Username = "user20"
                        });
                });

            modelBuilder.Entity("MinimalApi.Models.TodoItem", b =>
                {
                    b.HasOne("MinimalApi.Models.User", "User")
                        .WithMany("Todos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MinimalApi.Models.User", b =>
                {
                    b.Navigation("Todos");
                });
#pragma warning restore 612, 618
        }
    }
}
